import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { GeneratedFile } from '../emit';
import { isNotFound } from '../loader/fs';

export interface WriteResult {
	written: string[];
	/** Already as generated, so not touched: a watcher sees no change. */
	unchanged: string[];
	/**
	 * In check mode, the files that differ from what would be generated, are
	 * missing, or were generated before and no longer are.
	 */
	drifted: string[];
	/** Files an earlier run generated that this one does not: deleted. */
	removed: string[];
}

/** How every generated file starts. A file without it is never deleted. */
const GENERATED = '// Generated by @nxgt/openapi-codegen';

/**
 * Writes each file whose content changed. With `check`, writes nothing and
 * reports what would change instead — for CI.
 *
 * `retired` lists paths an earlier run may have generated: each one this run
 * does not generate is deleted when it still carries the generated header,
 * so turning an option off leaves no stale file behind.
 */
export async function writeFiles(
	files: readonly GeneratedFile[],
	{
		check = false,
		retired = [],
	}: { check?: boolean; retired?: readonly string[] } = {},
): Promise<WriteResult> {
	const result: WriteResult = {
		written: [],
		unchanged: [],
		drifted: [],
		removed: [],
	};
	for (const file of files) {
		if ((await current(file.path)) === file.content) {
			result.unchanged.push(file.path);
		} else if (check) {
			result.drifted.push(file.path);
		} else {
			await mkdir(dirname(file.path), { recursive: true });
			await writeFile(file.path, file.content);
			result.written.push(file.path);
		}
	}
	for (const path of retired) {
		if (files.some((file) => file.path === path)) continue;
		if (!(await current(path))?.startsWith(GENERATED)) continue;
		if (check) {
			result.drifted.push(path);
		} else {
			await rm(path);
			result.removed.push(path);
		}
	}
	return result;
}

async function current(path: string): Promise<string | undefined> {
	try {
		return await readFile(path, 'utf8');
	} catch (error) {
		if (isNotFound(error)) return undefined;
		throw error;
	}
}
