import { afterAll, describe, expect, it } from 'bun:test';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CodegenError } from './errors';
import { type GenerateOptions, generate, generateFiles } from './generate';
import { createMemoryFileSystem } from './loader/fs';

const SPEC = JSON.stringify({
	openapi: '3.1.0',
	info: { title: 't', version: '1' },
	paths: {},
	components: {
		schemas: {
			Pet: { type: 'object', properties: { name: { type: 'string' } } },
		},
	},
});

const dirs: string[] = [];
afterAll(() => Promise.all(dirs.map((dir) => rm(dir, { recursive: true }))));

async function project(): Promise<string> {
	const dir = await mkdtemp(join(tmpdir(), 'openapi-codegen-'));
	dirs.push(dir);
	await writeFile(join(dir, 'openapi.json'), SPEC);
	return dir;
}

describe('generate', () => {
	it('writes the files, then leaves them alone when nothing changed', async () => {
		const cwd = await project();
		const options = { input: 'openapi.json', output: 'gen' };
		const first = await generate(options, { cwd });
		expect(first.written.map((p) => p.slice(cwd.length))).toEqual([
			'/gen/types.gen.ts',
			'/gen/zod.gen.ts',
		]);
		expect(await readFile(join(cwd, 'gen/types.gen.ts'), 'utf8')).toStartWith(
			'// Generated by @nxgt/openapi-codegen from ../openapi.json. Do not edit.\n',
		);
		const second = await generate(options, { cwd });
		expect([second.written.length, second.unchanged.length]).toEqual([0, 2]);
	});

	it('reports drift in check mode without writing', async () => {
		const cwd = await project();
		const options = { input: 'openapi.json', output: 'gen', check: true };
		const missing = await generate(options, { cwd });
		expect([missing.drifted.length, missing.written.length]).toEqual([2, 0]);
		await generate({ ...options, check: false }, { cwd });
		await writeFile(join(cwd, 'gen/zod.gen.ts'), '// edited\n');
		const edited = await generate(options, { cwd });
		expect(edited.drifted.map((p) => p.slice(cwd.length))).toEqual([
			'/gen/zod.gen.ts',
		]);
	});

	it('refuses an option it does not know', async () => {
		const fs = createMemoryFileSystem({ '/s/openapi.json': SPEC });
		for (const bad of [
			{ unknownKeys: 'passthrough' },
			{ importExtension: '.mjs' },
		]) {
			const options = {
				input: '/s/openapi.json',
				output: '/s/gen',
				...bad,
			} as unknown as GenerateOptions;
			const error = await generateFiles(options, { fs }).catch(
				(e: unknown) => e,
			);
			expect(error).toBeInstanceOf(CodegenError);
			expect((error as CodegenError).diagnostics[0]?.code).toBe(
				'invalid_option',
			);
		}
	});

	it('honours unknownKeys and importExtension', async () => {
		const fs = createMemoryFileSystem({ '/s/openapi.json': SPEC });
		const { files } = await generateFiles(
			{
				input: '/s/openapi.json',
				output: '/s/gen',
				unknownKeys: 'loose',
			},
			{ fs },
		);
		const [types, zod] = files.map((f) => f.content);
		expect(zod).toContain('export const zPet = z.looseObject({');
		expect(types).toContain('[key: string]: unknown;');
	});
});
