import { afterAll, describe, expect, it } from 'bun:test';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CodegenError } from './errors';
import { type GenerateOptions, generate, generateFiles } from './generate';
import { createMemoryFileSystem } from './loader/fs';

const SPEC = JSON.stringify({
	openapi: '3.1.0',
	info: { title: 't', version: '1' },
	paths: {},
	components: {
		schemas: {
			Pet: { type: 'object', properties: { name: { type: 'string' } } },
		},
	},
});

const dirs: string[] = [];
afterAll(() => Promise.all(dirs.map((dir) => rm(dir, { recursive: true }))));

async function project(): Promise<string> {
	const dir = await mkdtemp(join(tmpdir(), 'openapi-codegen-'));
	dirs.push(dir);
	await writeFile(join(dir, 'openapi.json'), SPEC);
	return dir;
}

describe('generate', () => {
	it('writes the files, then leaves them alone when nothing changed', async () => {
		const cwd = await project();
		const options = { input: 'openapi.json', output: 'gen' };
		const first = await generate(options, { cwd });
		expect(first.written.map((p) => p.slice(cwd.length))).toEqual([
			'/gen/types.gen.ts',
			'/gen/zod.gen.ts',
			'/gen/operations.gen.ts',
			'/gen/paths.gen.ts',
		]);
		expect(await readFile(join(cwd, 'gen/types.gen.ts'), 'utf8')).toStartWith(
			'// Generated by @nxgt/openapi-codegen from ../openapi.json. Do not edit.\n',
		);
		const second = await generate(options, { cwd });
		expect([second.written.length, second.unchanged.length]).toEqual([0, 4]);
	});

	it('reports drift in check mode without writing', async () => {
		const cwd = await project();
		const options = { input: 'openapi.json', output: 'gen', check: true };
		const missing = await generate(options, { cwd });
		expect([missing.drifted.length, missing.written.length]).toEqual([4, 0]);
		await generate({ ...options, check: false }, { cwd });
		await writeFile(join(cwd, 'gen/zod.gen.ts'), '// edited\n');
		const edited = await generate(options, { cwd });
		expect(edited.drifted.map((p) => p.slice(cwd.length))).toEqual([
			'/gen/zod.gen.ts',
		]);
	});

	it('refuses an option it does not know', async () => {
		const fs = createMemoryFileSystem({ '/s/openapi.json': SPEC });
		for (const bad of [
			{ unknownKeys: 'passthrough' },
			{ importExtension: '.mjs' },
		]) {
			const options = {
				input: '/s/openapi.json',
				output: '/s/gen',
				...bad,
			} as unknown as GenerateOptions;
			const error = await generateFiles(options, { fs }).catch(
				(e: unknown) => e,
			);
			expect(error).toBeInstanceOf(CodegenError);
			expect((error as CodegenError).diagnostics[0]?.code).toBe(
				'invalid_option',
			);
		}
	});

	it('honours unknownKeys and importExtension', async () => {
		const fs = createMemoryFileSystem({ '/s/openapi.json': SPEC });
		const { files } = await generateFiles(
			{
				input: '/s/openapi.json',
				output: '/s/gen',
				unknownKeys: 'loose',
			},
			{ fs },
		);
		const [types, zod] = files.map((f) => f.content);
		expect(zod).toContain('export const zPet = z.looseObject({');
		expect(types).toContain('[key: string]: unknown;');
	});

	it('keeps each intersection member strict, and warns when the spec is loosened', async () => {
		const object = (key: string) => ({
			type: 'object',
			properties: { [key]: { type: 'string' } },
		});
		const spec = JSON.stringify({
			openapi: '3.1.0',
			info: { title: 't', version: '1' },
			paths: {},
			components: {
				schemas: {
					A: object('a'),
					U: { oneOf: [object('x'), object('y')] },
					C: {
						allOf: [
							{ $ref: '#/components/schemas/A' },
							{ $ref: '#/components/schemas/U' },
						],
					},
					Said: { ...object('d'), additionalProperties: false },
					Loosened: {
						allOf: [
							{ $ref: '#/components/schemas/Said' },
							{ $ref: '#/components/schemas/U' },
						],
					},
				},
			},
		});
		const fs = createMemoryFileSystem({ '/s/openapi.json': spec });
		const run = (unknownKeys: 'strict' | 'strip') =>
			generateFiles(
				{ input: '/s/openapi.json', output: '/s/gen', unknownKeys },
				{ fs },
			);
		// A Zod intersection refuses a key only when every member does: all strict is strict.
		const strict = await run('strict');
		const zod = strict.files[1]?.content ?? '';
		expect(zod).toContain('export const zA = z.strictObject({');
		expect(zod).toContain('export const zC = zA.and(zU);');
		expect(strict.warnings.map((w) => w.code)).not.toContain('not_enforced');
		// Beside members that strip, the spec's own `false` cannot refuse anything.
		const strip = await run('strip');
		const loosened = strip.warnings.filter((w) => w.code === 'not_enforced');
		expect(loosened).toHaveLength(1);
		expect(loosened[0]?.message).toStartWith(
			'Loosened: `additionalProperties: false`',
		);
	});

	const enumSpec = (status: Record<string, unknown>) =>
		createMemoryFileSystem({
			'/s/openapi.json': JSON.stringify({
				openapi: '3.1.0',
				info: { title: 't', version: '1' },
				paths: {},
				components: { schemas: { Status: status } },
			}),
		});

	it('prints a named enum as an object, or as a union with enums: union', async () => {
		const fs = enumSpec({
			type: ['string', 'null'],
			enum: ['active', 'on_leave', null],
			'x-enum-varnames': ['Active', 'OnLeave', 'None'],
		});
		const options = { input: '/s/openapi.json', output: '/s/gen' };
		const object = await generateFiles(options, { fs });
		const [types, zod] = object.files.map((f) => f.content);
		expect(types).toContain(
			"export const Status = {\n\tActive: 'active',\n\tOnLeave: 'on_leave',\n} as const;",
		);
		expect(types).toContain(
			'export type Status = (typeof Status)[keyof typeof Status] | null;',
		);
		expect(zod).toContain("import { Status } from './types.gen.js';");
		expect(zod).toContain('export const zStatus = z.enum(Status).nullable();');
		const union = await generateFiles({ ...options, enums: 'union' }, { fs });
		expect(union.files[0]?.content).not.toContain('export const Status');
		expect(union.files[1]?.content).toContain(
			"export const zStatus = z.enum(['active', 'on_leave']).nullable();",
		);
		await expect(
			generateFiles({ ...options, enums: 'native' as never }, { fs }),
		).rejects.toThrow('enums must be object or union, not native');
	});

	it('refuses an x-enum-varnames that does not name every value', async () => {
		const fs = enumSpec({ enum: ['a', 'b'], 'x-enum-varnames': ['A'] });
		const error = await generateFiles(
			{ input: '/s/openapi.json', output: '/s/gen' },
			{ fs },
		).catch((caught: unknown) => caught);
		expect(error).toBeInstanceOf(CodegenError);
		expect((error as CodegenError).diagnostics.map((d) => d.code)).toEqual([
			'invalid_schema',
		]);
	});

	it('refuses a schema named like an index the files declare', async () => {
		const named = (name: string) =>
			createMemoryFileSystem({
				'/s/openapi.json': JSON.stringify({
					openapi: '3.1.0',
					info: { title: 't', version: '1' },
					paths: {},
					components: { schemas: { [name]: { type: 'object' } } },
				}),
			});
		const options = { input: '/s/openapi.json', output: '/s/gen' };
		const refused = async (name: string, hono = false) => {
			const error = await generateFiles(
				{ ...options, hono },
				{ fs: named(name) },
			).catch((caught: unknown) => caught);
			if (!(error instanceof CodegenError)) return undefined;
			return error.diagnostics.map((d) => d.code);
		};
		expect(await refused('PathsByTag')).toEqual(['name_collision']);
		expect(await refused('Replies')).toBeUndefined();
		expect(await refused('Replies', true)).toEqual(['name_collision']);
	});
});
