/**
 * Writes the generated code of every fixture under `test/generated/`, which
 * git ignores. The runtime specs import it, and `tsc` checks it, including
 * each case's `agreement.ts`: one line per schema and per parameter
 * validator, which fails to compile when a type and its validator disagree.
 *
 * The package's `test` and `typecheck` scripts run this first. What the code
 * looks like is pinned by the snapshots of `src/emit/golden.spec.ts`.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GeneratedFile } from '../src/emit';
import { EmitContext, paramGroups } from '../src/emit/context';
import { file, jsString } from '../src/emit/printer';
import { generateFiles } from '../src/generate';
import { createMemoryFileSystem } from '../src/index';
import { buildIR } from '../src/ir';
import { loadDocument } from '../src/loader/document';
import { PERF_SIZE, perfRoutes, perfSpec } from './perf';

const TEST_DIR = fileURLToPath(new URL('./', import.meta.url));
export const CASES = ['split', 'query', 'kitchen-sink'] as const;

/** A fixture's generated files, then its `agreement.ts`, with absolute paths. */
export async function fixtureFiles(name: string): Promise<GeneratedFile[]> {
	const input = `${TEST_DIR}fixtures/${name}/openapi.yaml`;
	const output = `${TEST_DIR}generated/${name}`;
	const { files } = await generateFiles({ input, output, hono: true });
	return [
		...files,
		{ path: `${output}/agreement.ts`, content: await agreement(input) },
	];
}

/**
 * The perf case: `PERF_SIZE` generated operations, a route for each, and a
 * `tsconfig.json` so `src/hono/perf.spec.ts` can measure them alone.
 */
export async function perfFiles(): Promise<GeneratedFile[]> {
	const input = '/perf/openapi.json';
	const output = `${TEST_DIR}generated/perf`;
	const { files } = await generateFiles(
		{ input, output, hono: true },
		{
			fs: createMemoryFileSystem({
				[input]: JSON.stringify(perfSpec(PERF_SIZE)),
			}),
		},
	);
	return [
		...files,
		{ path: `${output}/routes.ts`, content: perfRoutes(PERF_SIZE) },
		// With the routes, and without: the difference is what the routes cost.
		tsconfig(`${output}/tsconfig.json`, { include: ['./*.ts'] }),
		tsconfig(`${output}/tsconfig.base.json`, { files: ['./hono.gen.ts'] }),
	];
}

function tsconfig(path: string, sources: object): GeneratedFile {
	const config = {
		extends: '../../../tsconfig.json',
		compilerOptions: { rootDir: '../../..', noEmit: true },
		...sources,
	};
	return { path, content: `${JSON.stringify(config, null, '\t')}\n` };
}

async function agreement(input: string): Promise<string> {
	const ir = buildIR(await loadDocument(input));
	const ctx = new EmitContext(ir, {
		unknownKeys: 'strip',
		enums: 'object',
		importExtension: '.js',
		hono: true,
		source: '',
		rootDir: TEST_DIR,
	});
	const schemas = [
		...ir.schemas.map((s) => ({ name: s.name, id: s.id })),
		...ir.aliases.map((a) => ({ name: a.name, id: a.target })),
	].flatMap(({ name, id }) => [
		`\tAgree<Equal<z.output<typeof Z.z${name}>, T.${name}>>,`,
		`\tAgree<Equal<z.input<typeof Z.z${name}>, T.${ctx.typeName(id, true).replace(ctx.schema(id).name, name)}>>,`,
	]);
	// Only the output: a parameter validator takes strings, whatever the type says.
	const parameters = ir.operations
		.flatMap((operation) => paramGroups(operation))
		.map(
			(group) =>
				`\tAgree<Equal<z.output<typeof O.z${group.name}>, T.${group.name}>>,`,
		);
	// A form validator reads text, but returns what the operation's form type says.
	const forms = ir.operations
		.filter((operation) => ctx.formOf(operation))
		.map(
			(operation) =>
				`\tAgree<Equal<z.output<typeof O.z${operation.name}Form>, NonNullable<T.Operations[${jsString(operation.operationId)}]['form']>>>,`,
		);
	parameters.push(...forms);
	const imports = [
		"import type { z } from 'zod';",
		...(parameters.length > 0
			? ["import type * as O from './operations.gen.js';"]
			: []),
		"import type * as T from './types.gen.js';",
		"import type * as Z from './zod.gen.js';",
	];
	const checks = [...schemas, ...parameters];
	return file([
		'// Generated by test/generate.ts: tsc fails here when a type disagrees with its validator.',
		imports.join('\n'),
		[
			'type Equal<X, Y> = 0 extends 1 & X',
			'\t? false',
			'\t: 0 extends 1 & Y',
			'\t\t? false',
			'\t\t: [X] extends [Y]',
			'\t\t\t? [Y] extends [X]',
			'\t\t\t\t? true',
			'\t\t\t\t: false',
			'\t\t\t: false;',
			'type Agree<Result extends true> = Result;',
		].join('\n'),
		checks.length === 0
			? 'export type Agreement = [];'
			: `export type Agreement = [\n${checks.join('\n')}\n];`,
	]);
}

if (import.meta.main) {
	// From scratch, so a file the generator stopped writing does not linger.
	await rm(`${TEST_DIR}generated`, { recursive: true, force: true });
	const cases = await Promise.all(CASES.map((name) => fixtureFiles(name)));
	for (const generated of [...cases.flat(), ...(await perfFiles())]) {
		await mkdir(dirname(generated.path), { recursive: true });
		await writeFile(generated.path, generated.content);
	}
}
