/**
 * Writes the generated code of every fixture under `test/generated/`, which
 * git ignores. The runtime specs import it, and `tsc` checks it, including
 * each case's `agreement.ts`: one line per schema and per parameter
 * validator, which fails to compile when a type and its validator disagree.
 *
 * The package's `test` and `typecheck` scripts run this first. What the code
 * looks like is pinned by the snapshots of `src/emit/golden.spec.ts`.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { GeneratedFile } from '../src/emit';
import { type Dates, EmitContext, paramGroups } from '../src/emit/context';
import { file, jsString } from '../src/emit/printer';
import { generateFiles } from '../src/generate';
import { buildIR } from '../src/ir';
import { loadDocument } from '../src/loader/document';

const TEST_DIR = fileURLToPath(new URL('./', import.meta.url));
export const CASES = [
	'split',
	'query',
	'kitchen-sink',
	'dates',
	'streams',
] as const;

/** Real, public specs under `fixtures/conformance/`: generated and type-checked, not snapshotted. */
export const CONFORMANCE = [
	'redocly-museum',
	'oai-tictactoe',
	'oai-webhook',
	'oai-query-3.2',
	'oai-tags-3.2',
] as const;

/** What a case is generated with, beside `hono`. */
const OPTIONS: { [name: string]: { dates?: Dates } } = {
	dates: { dates: 'date' },
	// Dated, so a stream's items are typed both decoded and as JSON carries them.
	streams: { dates: 'date' },
};

/** A fixture's generated files, then its `agreement.ts`, with absolute paths. */
export async function fixtureFiles(name: string): Promise<GeneratedFile[]> {
	const input = `${TEST_DIR}fixtures/${name}/openapi.yaml`;
	const output = `${TEST_DIR}generated/${name}`;
	const options = OPTIONS[name] ?? {};
	const { files } = await generateFiles({
		input,
		output,
		hono: true,
		...options,
	});
	return [
		...files,
		{
			path: `${output}/agreement.ts`,
			content: await agreement(input, options),
		},
	];
}

async function agreement(
	input: string,
	options: { dates?: Dates },
): Promise<string> {
	const ir = buildIR(await loadDocument(input));
	const ctx = new EmitContext(ir, {
		unknownKeys: 'strip',
		enums: 'object',
		importExtension: '.js',
		hono: true,
		source: '',
		rootDir: TEST_DIR,
		...options,
	});
	const schemas = [
		...ir.schemas.map((s) => ({ name: s.name, id: s.id })),
		...ir.aliases.map((a) => ({ name: a.name, id: a.target })),
	].flatMap(({ name, id }) => [
		`\tAgree<Equal<z.output<typeof Z.z${name}>, T.${name}>>,`,
		`\tAgree<Equal<z.input<typeof Z.z${name}>, T.${ctx.typeName(id, true).replace(ctx.schema(id).name, name)}>>,`,
	]);
	// Only the output: a parameter validator takes strings, whatever the type says.
	const parameters = ir.operations
		.flatMap((operation) => paramGroups(operation))
		.map(
			(group) =>
				`\tAgree<Equal<z.output<typeof O.z${group.name}>, T.${group.name}>>,`,
		);
	// A form validator reads text, but returns what the operation's form type says.
	const forms = ir.operations
		.filter((operation) => ctx.formOf(operation))
		.map(
			(operation) =>
				`\tAgree<Equal<z.output<typeof O.z${operation.name}Form>, NonNullable<T.Operations[${jsString(operation.operationId)}]['form']>>>,`,
		);
	parameters.push(...forms);
	const imports = [
		"import type { z } from 'zod';",
		...(parameters.length > 0
			? ["import type * as O from './operations.js';"]
			: []),
		"import type * as T from './types.js';",
		"import type * as Z from './zod.js';",
	];
	const checks = [...schemas, ...parameters];
	// Nothing to agree on: no import left unused under the strict typecheck.
	if (checks.length === 0) {
		return file([
			'// Generated by test/generate.ts: the spec has no schema to check.',
			'export {};',
		]);
	}
	return file([
		'// Generated by test/generate.ts: tsc fails here when a type disagrees with its validator.',
		imports.join('\n'),
		[
			'type Equal<X, Y> = 0 extends 1 & X',
			'\t? false',
			'\t: 0 extends 1 & Y',
			'\t\t? false',
			'\t\t: [X] extends [Y]',
			'\t\t\t? [Y] extends [X]',
			'\t\t\t\t? true',
			'\t\t\t\t: false',
			'\t\t\t: false;',
			'type Agree<Result extends true> = Result;',
		].join('\n'),
		checks.length === 0
			? 'export type Agreement = [];'
			: `export type Agreement = [\n${checks.join('\n')}\n];`,
	]);
}

if (import.meta.main) {
	// From scratch, so a file the generator stopped writing does not linger.
	await rm(`${TEST_DIR}generated`, { recursive: true, force: true });
	const names = [...CASES, ...CONFORMANCE.map((name) => `conformance/${name}`)];
	const cases = await Promise.all(names.map((name) => fixtureFiles(name)));
	for (const generated of cases.flat()) {
		await mkdir(dirname(generated.path), { recursive: true });
		await writeFile(generated.path, generated.content);
	}
}
