import { CodegenError, type Diagnostic } from '../errors';
import type {
	ApiIR,
	LiteralNode,
	MediaIR,
	NamedSchema,
	ObjectNode,
	OperationIR,
	ParamIR,
	Property,
	SchemaNode,
} from '../ir/types';
import type { Location } from '../loader/location';

/** What an object does with keys it does not declare, when the spec does not say. */
export type UnknownKeys = 'strip' | 'strict' | 'loose';

/** A named enum as an `as const` object that `z.enum()` reuses, or as a plain union. */
export type Enums = 'object' | 'union';

/** A `date-time` as the string JSON carries, or decoded to a `Date`. */
export type Dates = 'string' | 'date';

/** What an object does with undeclared keys once the `unknownKeys` default is applied. */
export type ObjectMode = UnknownKeys | { schema: SchemaNode };

export interface EmitOptions {
	unknownKeys: UnknownKeys;
	enums: Enums;
	/** Appended to imports between generated files: `.js` works under every `moduleResolution`. */
	importExtension: '' | '.js' | '.ts';
	/** The spec, relative to the output directory, for the header. */
	source: string;
	/** Where diagnostics are reported relative to. */
	rootDir: string;
	/** Also emit `hono.ts`. */
	hono?: boolean;
	/** `date-time` as a string (the default), or decoded to a `Date` by a codec. */
	dates?: Dates;
}

/** A property whose default the validator fills in: optional going in, present coming out. */
export const appliesDefault = (property: Property): boolean =>
	!property.required && property.schema.default !== undefined;

/** What `types.ts` declares beside the schemas, printed by `operationTypes`. */
export const OPERATION_INDEXES = [
	'Operations',
	'OperationsByRoute',
	'PathsByMethod',
	'OperationsByTag',
	'PathsByTag',
] as const;

/** An operation's route, its key in `OperationsByRoute`: `put /employees/{id}`. */
export const routeKey = (operation: OperationIR): string =>
	`${operation.method} ${operation.path}`;

/** Header names are case-insensitive: validated headers are keyed lowercased, as Hono reads them. */
export const paramKey = (param: ParamIR): string =>
	param.in === 'header' ? param.name.toLowerCase() : param.name;

/** An operation's parameters in one location, validated together. */
export interface ParamGroup {
	/** Where Hono's `c.req.valid()` finds them. */
	target: 'param' | 'query' | 'header';
	/** `GetPetQuery`, whose validator is `zGetPetQuery`. */
	name: string;
	params: ParamIR[];
}

const GROUPS = [
	['path', 'param', 'Param'],
	['query', 'query', 'Query'],
	['header', 'header', 'Header'],
] as const;

export function paramGroups(operation: OperationIR): ParamGroup[] {
	return GROUPS.flatMap(([location, target, suffix]) => {
		const params = operation.parameters.filter((p) => p.in === location);
		if (params.length === 0) return [];
		return [{ target, name: `${operation.name}${suffix}`, params }];
	});
}

/** The IR plus what both emitters need to agree on. */
export class EmitContext {
	readonly ir: ApiIR;
	readonly options: EmitOptions;
	readonly #byId: Map<string, NamedSchema>;
	/** Schemas whose validator accepts something other than what it returns. */
	readonly #inputs = new Set<string>();
	/** With `dates: 'date'`, schemas whose values hold a `Date`. */
	readonly #dated = new Set<string>();
	/** What the generated code accepts but the spec would refuse. */
	readonly warnings: Diagnostic[] = [];
	/** While set, every name `typeName` gives out, for a file that imports them. */
	#typeUses: Set<string> | undefined;

	constructor(ir: ApiIR, options: EmitOptions) {
		this.ir = ir;
		this.options = options;
		this.#byId = new Map(ir.schemas.map((schema) => [schema.id, schema]));
		this.#fixpoint(this.#dated, (node) => this.datesIn(node));
		this.#fixpoint(this.#inputs, (node) => this.inputDiffers(node));
		this.#findLoosened();
		this.#checkNames();
	}

	get header(): string {
		return `// Generated by @nxgt/openapi-codegen from ${this.options.source}. Do not edit.`;
	}

	schema(id: string): NamedSchema {
		const schema = this.#byId.get(id);
		if (!schema) throw new Error(`openapi-codegen: no schema ${id}`);
		return schema;
	}

	/** Whether the schema needs a separate `XInput` type. */
	hasInput(id: string): boolean {
		return this.#inputs.has(id);
	}

	/** `Employee`, or `EmployeeInput` on the input side when the two differ. */
	typeName(id: string, input: boolean): string {
		const { name } = this.schema(id);
		const out = input && this.#inputs.has(id) ? `${name}Input` : name;
		this.#typeUses?.add(out);
		return out;
	}

	/**
	 * The node of a named schema printed as an `as const` object: an `enum` of
	 * two or more strings or numbers. `z.enum()` takes no booleans, and a
	 * single value is a constant, not a choice.
	 */
	enumOf(id: string): LiteralNode | undefined {
		if (this.options.enums !== 'object') return undefined;
		const { node } = this.schema(id);
		return node.kind === 'literal' &&
			node.values.length > 1 &&
			node.values.every(
				(value) => typeof value === 'string' || typeof value === 'number',
			)
			? node
			: undefined;
	}

	/**
	 * The operation's form body, when its fields can be read from text: an
	 * object with no `allOf` parent and no schema for extra keys. It gets a
	 * validator of its own, `z<Operation>Form`.
	 */
	formOf(
		operation: OperationIR,
	): { media: MediaIR; object: ObjectNode } | undefined {
		const media = operation.body?.content.find((m) => m.kind === 'form');
		if (!media?.schema || media.schema.nullable) return undefined;
		const object = this.resolve(media.schema);
		return object.kind === 'object' &&
			!object.nullable &&
			object.extends.length === 0 &&
			typeof object.additional !== 'object'
			? { media, object }
			: undefined;
	}

	/** Runs `print`, and returns what it printed and every type name it used. */
	collectTypes<T>(print: () => T): { value: T; names: Set<string> } {
		const outer = this.#typeUses;
		const names = new Set<string>();
		this.#typeUses = names;
		try {
			return { value: print(), names };
		} finally {
			this.#typeUses = outer;
		}
	}

	resolve(node: SchemaNode): SchemaNode {
		let current = node;
		for (let hops = 0; current.kind === 'ref' && hops < 64; hops++) {
			current = this.schema(current.target).node;
		}
		return current;
	}

	/**
	 * The object's unknown-key mode. An intersection member keeps its own: a
	 * Zod intersection reports an unknown key only when every member does.
	 */
	mode(node: ObjectNode): ObjectMode {
		return node.additional === 'default'
			? this.options.unknownKeys
			: node.additional;
	}

	/** The mode of a named object schema. */
	modeOf(id: string): ObjectMode {
		const node = this.resolve(this.schema(id).node);
		return node.kind === 'object' ? this.mode(node) : 'strip';
	}

	/** A property of `object`, its own or one it extends. */
	propertyOf(
		object: ObjectNode,
		name: string,
		seen = new Set<string>(),
	): Property | undefined {
		const own = object.properties.find((p) => p.name === name);
		if (own) return own;
		for (const id of object.extends) {
			if (seen.has(id)) continue;
			seen.add(id);
			const parent = this.resolve(this.schema(id).node);
			if (parent.kind !== 'object') continue;
			const found = this.propertyOf(parent, name, seen);
			if (found) return found;
		}
		return undefined;
	}

	/**
	 * Whether the node's validator is a `ZodObject`, which `.extend()` and
	 * `discriminatedUnion` need. A recursive schema is typed `ZodType`, and an
	 * object built on one is an intersection.
	 */
	isZodObject(node: SchemaNode): boolean {
		if (node.nullable) return false;
		if (node.kind === 'ref') {
			const schema = this.schema(node.target);
			return !schema.recursive && this.isZodObject(schema.node);
		}
		return (
			node.kind === 'object' &&
			node.extends.every((target) => this.isZodObject({ kind: 'ref', target }))
		);
	}

	/** A `date-time` that the validator decodes to a `Date`: with `dates: 'date'` only. */
	isDate(node: SchemaNode): boolean {
		return (
			this.options.dates === 'date' &&
			node.kind === 'string' &&
			node.format === 'date-time'
		);
	}

	/** Whether a value of the node holds a decoded `Date`, anywhere inside. */
	datesIn(node: SchemaNode): boolean {
		switch (node.kind) {
			case 'string':
				return this.isDate(node);
			case 'ref':
				return this.#dated.has(node.target);
			case 'array':
				return this.datesIn(node.items);
			case 'record':
				return this.datesIn(node.values);
			case 'union':
				return node.variants.some((variant) => this.datesIn(variant));
			case 'intersection':
				return node.members.some((member) => this.datesIn(member));
			case 'object':
				return (
					node.extends.some((id) => this.#dated.has(id)) ||
					node.properties.some((p) => this.datesIn(p.schema)) ||
					(typeof node.additional === 'object' &&
						this.datesIn(node.additional.schema))
				);
			default:
				return false;
		}
	}

	/**
	 * `text`, the type of `node`, as JSON carries it: `Wire<T>` when it holds a
	 * `Date`, which travels as its ISO string. Replies and `paths.ts`
	 * responses are typed this way; only a decoded value holds a `Date`.
	 */
	wire(node: SchemaNode, text: string): string {
		if (!this.datesIn(node)) return text;
		this.#typeUses?.add('Wire');
		return `Wire<${text}>`;
	}

	/** Whether the node's validator accepts something other than what it returns. */
	inputDiffers(node: SchemaNode): boolean {
		switch (node.kind) {
			case 'string':
				// A codec takes the string and returns the Date.
				return this.isDate(node);
			case 'ref':
				return this.#inputs.has(node.target);
			case 'array':
				return this.inputDiffers(node.items);
			case 'record':
				return this.inputDiffers(node.values);
			case 'union':
				return node.variants.some((variant) => this.inputDiffers(variant));
			case 'intersection':
				return node.members.some((member) => this.inputDiffers(member));
			case 'object':
				return (
					node.extends.some((id) => this.#inputs.has(id)) ||
					node.properties.some(
						(p) => appliesDefault(p) || this.inputDiffers(p.schema),
					) ||
					(typeof node.additional === 'object' &&
						this.inputDiffers(node.additional.schema))
				);
			default:
				return false;
		}
	}

	/** The schemas whose node `holds`, to a fixpoint, since schemas can reach each other in cycles. */
	#fixpoint(set: Set<string>, holds: (node: SchemaNode) => boolean): void {
		let changed = true;
		while (changed) {
			changed = false;
			for (const schema of this.ir.schemas) {
				if (set.has(schema.id) || !holds(schema.node)) continue;
				set.add(schema.id);
				changed = true;
			}
		}
	}

	/**
	 * An `additionalProperties: false` on an `allOf` member that the generated
	 * validator cannot keep. JSON Schema refuses every key that member does not
	 * declare. A Zod intersection refuses a key only when every member does,
	 * and `.extend()` takes the child's mode, so beside a member that strips
	 * the extra keys are dropped instead.
	 */
	#findLoosened(): void {
		const refuses = (
			node: SchemaNode,
			seen = new Set<SchemaNode>(),
		): boolean => {
			const target = this.resolve(node);
			if (seen.has(target)) return true;
			seen.add(target);
			switch (target.kind) {
				case 'object':
					return this.mode(target) === 'strict';
				case 'union':
					return target.variants.every((v) => refuses(v, seen));
				case 'intersection':
					return target.members.some((m) => refuses(m, seen));
				case 'record':
				case 'unknown':
					// Any key goes.
					return false;
				default:
					return true;
			}
		};
		const said = (node: SchemaNode): boolean => {
			const target = this.resolve(node);
			return target.kind === 'object' && target.additional === 'strict';
		};
		for (const schema of this.ir.schemas) {
			let loosened = false;
			let unsealed = false;
			const visit = (node: SchemaNode): void => {
				if (node.kind === 'array') visit(node.items);
				else if (node.kind === 'record') visit(node.values);
				else if (node.kind === 'ref') {
					if (node.sealed && !refuses(node)) unsealed = true;
				} else if (node.kind === 'union') {
					if (node.sealed && !node.variants.every((v) => refuses(v))) {
						unsealed = true;
					}
					node.variants.forEach(visit);
				} else if (node.kind === 'intersection') {
					if (node.sealed && !node.members.every((m) => refuses(m))) {
						unsealed = true;
					}
					if (
						node.members.some(said) &&
						!node.members.every((m) => refuses(m))
					) {
						loosened = true;
					}
					node.members.forEach(visit);
				} else if (node.kind === 'object') {
					const parents = node.extends.map(
						(target): SchemaNode => ({ kind: 'ref', target }),
					);
					const strict = this.mode(node) === 'strict';
					// Without properties of its own, or of a parent's that `required`
					// restates, the object adds no member to the intersection.
					const shapeless =
						node.properties.length === 0 &&
						!(node.requires ?? []).some(
							(name) => this.propertyOf(node, name) !== undefined,
						);
					const kept = parents.every((p) => this.isZodObject(p))
						? strict
						: parents.every((p) => refuses(p)) && (strict || shapeless);
					if (parents.some(said) && !kept) loosened = true;
					for (const property of node.properties) visit(property.schema);
					if (typeof node.additional === 'object') {
						visit(node.additional.schema);
					}
				}
			};
			visit(schema.node);
			if (unsealed) {
				this.warnings.push({
					severity: 'warning',
					code: 'not_enforced',
					message: `${schema.name}: \`unevaluatedProperties: false\` is not enforced over a $ref member that accepts keys it does not declare: they are dropped, not refused. Give that member \`additionalProperties: false\`, or set \`unknownKeys: 'strict'\``,
					file: schema.location.file,
					pointer: schema.location.pointer,
				});
			}
			if (!loosened) continue;
			this.warnings.push({
				severity: 'warning',
				code: 'not_enforced',
				message: `${schema.name}: \`additionalProperties: false\` on an allOf member is not enforced. A key it does not declare is dropped, not refused, when another member accepts it`,
				file: schema.location.file,
				pointer: schema.location.pointer,
			});
		}
	}

	/**
	 * Every generated name, once. A schema's `XInput`, an operation's `XQuery`,
	 * or a name `types.ts` and `hono.ts` declare themselves, can land
	 * on a name a schema already has. Interfaces of one name would merge, not
	 * fail, so this is the only place the clash is caught.
	 */
	#checkNames(): void {
		const owners = new Map<string, string>();
		const diagnostics: Diagnostic[] = [];
		const claim = (name: string, owner: string, at: Location): void => {
			const holder = owners.get(name);
			if (holder === undefined) {
				owners.set(name, owner);
				return;
			}
			diagnostics.push({
				severity: 'error',
				code: 'name_collision',
				message: `${holder} and ${owner} would both generate ${name}. Rename the schema with the \`names\` option`,
				file: at.file,
				pointer: at.pointer,
			});
		};
		const root = { file: this.options.rootDir, pointer: '' };
		for (const name of OPERATION_INDEXES) claim(name, 'types.ts', root);
		if (this.options.dates === 'date') claim('Wire', 'types.ts', root);
		if (this.options.hono) {
			// Declared or imported by hono.ts, which also imports schemas by name.
			for (const name of ['Replies', 'HonoSpec', 'Hono']) {
				claim(name, 'hono.ts', root);
			}
		}
		for (const schema of this.ir.schemas) {
			claim(schema.name, `schema ${schema.name}`, schema.location);
		}
		for (const alias of this.ir.aliases) {
			claim(alias.name, `schema ${alias.name}`, alias.location);
		}
		for (const schema of this.ir.schemas) {
			if (this.#inputs.has(schema.id)) {
				claim(`${schema.name}Input`, `schema ${schema.name}`, schema.location);
			}
		}
		for (const alias of this.ir.aliases) {
			if (this.#inputs.has(alias.target)) {
				claim(`${alias.name}Input`, `schema ${alias.name}`, alias.location);
			}
		}
		for (const operation of this.ir.operations) {
			const owner = `operation ${operation.operationId}`;
			for (const group of paramGroups(operation)) {
				claim(group.name, owner, operation.location);
			}
			if (this.formOf(operation)) {
				claim(`${operation.name}Form`, owner, operation.location);
			}
		}
		if (diagnostics.length > 0) {
			throw new CodegenError(diagnostics, this.options.rootDir);
		}
	}
}
