import { CodegenError, type Diagnostic } from '../errors';
import type {
	ApiIR,
	NamedSchema,
	ObjectNode,
	Property,
	SchemaNode,
} from '../ir/types';

/** What an object does with keys it does not declare, when the spec does not say. */
export type UnknownKeys = 'strip' | 'strict' | 'loose';

/** What an object does with undeclared keys once the `unknownKeys` default is applied. */
export type ObjectMode = UnknownKeys | { schema: SchemaNode };

export interface EmitOptions {
	unknownKeys: UnknownKeys;
	/** Appended to imports between generated files: `.js` works under every `moduleResolution`. */
	importExtension: '' | '.js' | '.ts';
	/** The spec, relative to the output directory, for the header. */
	source: string;
	/** Where diagnostics are reported relative to. */
	rootDir: string;
}

/** A property whose default the validator fills in: optional going in, present coming out. */
export const appliesDefault = (property: Property): boolean =>
	!property.required && property.schema.default !== undefined;

/** The IR plus what both emitters need to agree on. */
export class EmitContext {
	readonly ir: ApiIR;
	readonly options: EmitOptions;
	readonly #byId: Map<string, NamedSchema>;
	/** Schemas whose validator accepts something other than what it returns. */
	readonly #inputs = new Set<string>();

	constructor(ir: ApiIR, options: EmitOptions) {
		this.ir = ir;
		this.options = options;
		this.#byId = new Map(ir.schemas.map((schema) => [schema.id, schema]));
		this.#findInputs();
		this.#checkNames();
	}

	get header(): string {
		return `// Generated by @nxgt/openapi-codegen from ${this.options.source}. Do not edit.`;
	}

	schema(id: string): NamedSchema {
		const schema = this.#byId.get(id);
		if (!schema) throw new Error(`openapi-codegen: no schema ${id}`);
		return schema;
	}

	/** Whether the schema needs a separate `XInput` type. */
	hasInput(id: string): boolean {
		return this.#inputs.has(id);
	}

	/** `Employee`, or `EmployeeInput` on the input side when the two differ. */
	typeName(id: string, input: boolean): string {
		const { name } = this.schema(id);
		return input && this.#inputs.has(id) ? `${name}Input` : name;
	}

	resolve(node: SchemaNode): SchemaNode {
		let current = node;
		for (let hops = 0; current.kind === 'ref' && hops < 64; hops++) {
			current = this.schema(current.target).node;
		}
		return current;
	}

	/**
	 * The object's unknown-key mode. An object that is one member of an
	 * intersection strips when the spec does not say: each member of a Zod
	 * intersection parses the whole input, so a strict member would reject the
	 * other members' keys.
	 */
	mode(node: ObjectNode, member = false): ObjectMode {
		if (node.additional !== 'default') return node.additional;
		return member ? 'strip' : this.options.unknownKeys;
	}

	/** The mode of a named object schema. */
	modeOf(id: string): ObjectMode {
		const node = this.resolve(this.schema(id).node);
		return node.kind === 'object' ? this.mode(node) : 'strip';
	}

	/** A property of `object`, its own or one it extends. */
	propertyOf(
		object: ObjectNode,
		name: string,
		seen = new Set<string>(),
	): Property | undefined {
		const own = object.properties.find((p) => p.name === name);
		if (own) return own;
		for (const id of object.extends) {
			if (seen.has(id)) continue;
			seen.add(id);
			const parent = this.resolve(this.schema(id).node);
			if (parent.kind !== 'object') continue;
			const found = this.propertyOf(parent, name, seen);
			if (found) return found;
		}
		return undefined;
	}

	/**
	 * Whether the node's validator is a `ZodObject`, which `.extend()` and
	 * `discriminatedUnion` need. A recursive schema is typed `ZodType`, and an
	 * object built on one is an intersection.
	 */
	isZodObject(node: SchemaNode): boolean {
		if (node.nullable) return false;
		if (node.kind === 'ref') {
			const schema = this.schema(node.target);
			return !schema.recursive && this.isZodObject(schema.node);
		}
		return (
			node.kind === 'object' &&
			node.extends.every((target) => this.isZodObject({ kind: 'ref', target }))
		);
	}

	/** Whether the node's validator accepts something other than what it returns. */
	inputDiffers(node: SchemaNode): boolean {
		switch (node.kind) {
			case 'ref':
				return this.#inputs.has(node.target);
			case 'array':
				return this.inputDiffers(node.items);
			case 'record':
				return this.inputDiffers(node.values);
			case 'union':
				return node.variants.some((variant) => this.inputDiffers(variant));
			case 'intersection':
				return node.members.some((member) => this.inputDiffers(member));
			case 'object':
				return (
					node.extends.some((id) => this.#inputs.has(id)) ||
					node.properties.some(
						(p) => appliesDefault(p) || this.inputDiffers(p.schema),
					) ||
					(typeof node.additional === 'object' &&
						this.inputDiffers(node.additional.schema))
				);
			default:
				return false;
		}
	}

	/** To a fixpoint, since schemas can reach each other in cycles. */
	#findInputs(): void {
		let changed = true;
		while (changed) {
			changed = false;
			for (const schema of this.ir.schemas) {
				if (this.#inputs.has(schema.id) || !this.inputDiffers(schema.node)) {
					continue;
				}
				this.#inputs.add(schema.id);
				changed = true;
			}
		}
	}

	/** `Employee` wants `EmployeeInput`; a schema already called that is a collision. */
	#checkNames(): void {
		const owners = new Map<string, string>();
		const diagnostics: Diagnostic[] = [];
		const claim = (name: string, owner: NamedSchema): void => {
			const holder = owners.get(name);
			if (holder === undefined) {
				owners.set(name, owner.name);
				return;
			}
			diagnostics.push({
				severity: 'error',
				code: 'name_collision',
				message: `${holder} needs the name ${name} for its input type, and a schema already has it. Rename one with the \`names\` option`,
				file: owner.location.file,
				pointer: owner.location.pointer,
			});
		};
		for (const schema of this.ir.schemas) claim(schema.name, schema);
		for (const alias of this.ir.aliases) {
			claim(alias.name, { ...this.schema(alias.target), name: alias.name });
		}
		for (const schema of this.ir.schemas) {
			if (this.#inputs.has(schema.id)) claim(`${schema.name}Input`, schema);
		}
		for (const alias of this.ir.aliases) {
			if (this.#inputs.has(alias.target)) {
				claim(`${alias.name}Input`, {
					...this.schema(alias.target),
					name: alias.name,
				});
			}
		}
		if (diagnostics.length > 0) {
			throw new CodegenError(diagnostics, this.options.rootDir);
		}
	}
}
