import { CodegenError, type Diagnostic } from '../errors';
import type {
	ApiIR,
	LiteralNode,
	NamedSchema,
	ObjectNode,
	OperationIR,
	ParamIR,
	Property,
	SchemaNode,
} from '../ir/types';
import type { Location } from '../loader/location';

/** What an object does with keys it does not declare, when the spec does not say. */
export type UnknownKeys = 'strip' | 'strict' | 'loose';

/** A named enum as an `as const` object that `z.enum()` reuses, or as a plain union. */
export type Enums = 'object' | 'union';

/** What an object does with undeclared keys once the `unknownKeys` default is applied. */
export type ObjectMode = UnknownKeys | { schema: SchemaNode };

export interface EmitOptions {
	unknownKeys: UnknownKeys;
	enums: Enums;
	/** Appended to imports between generated files: `.js` works under every `moduleResolution`. */
	importExtension: '' | '.js' | '.ts';
	/** The spec, relative to the output directory, for the header. */
	source: string;
	/** Where diagnostics are reported relative to. */
	rootDir: string;
}

/** A property whose default the validator fills in: optional going in, present coming out. */
export const appliesDefault = (property: Property): boolean =>
	!property.required && property.schema.default !== undefined;

/** An operation's key in `Operations` and in the table: `put /employees/{id}`. */
export const operationKey = (operation: OperationIR): string =>
	`${operation.method} ${operation.path}`;

/** Header names are case-insensitive: validated headers are keyed lowercased, as Hono reads them. */
export const paramKey = (param: ParamIR): string =>
	param.in === 'header' ? param.name.toLowerCase() : param.name;

/** An operation's parameters in one location, validated together. */
export interface ParamGroup {
	/** Where Hono's `c.req.valid()` finds them. */
	target: 'param' | 'query' | 'header';
	/** `GetPetQuery`, whose validator is `zGetPetQuery`. */
	name: string;
	params: ParamIR[];
	/** A default makes what a caller passes differ from what a handler gets. */
	hasInput: boolean;
}

const GROUPS = [
	['path', 'param', 'Param'],
	['query', 'query', 'Query'],
	['header', 'header', 'Header'],
] as const;

export function paramGroups(operation: OperationIR): ParamGroup[] {
	return GROUPS.flatMap(([location, target, suffix]) => {
		const params = operation.parameters.filter((p) => p.in === location);
		if (params.length === 0) return [];
		return [
			{
				target,
				name: `${operation.name}${suffix}`,
				params,
				hasInput: params.some(
					(p) => !p.required && p.schema.default !== undefined,
				),
			},
		];
	});
}

/** The IR plus what both emitters need to agree on. */
export class EmitContext {
	readonly ir: ApiIR;
	readonly options: EmitOptions;
	readonly #byId: Map<string, NamedSchema>;
	/** Schemas whose validator accepts something other than what it returns. */
	readonly #inputs = new Set<string>();
	/** What the generated code accepts but the spec would refuse. */
	readonly warnings: Diagnostic[] = [];
	/** While set, every name `typeName` gives out, for a file that imports them. */
	#typeUses: Set<string> | undefined;

	constructor(ir: ApiIR, options: EmitOptions) {
		this.ir = ir;
		this.options = options;
		this.#byId = new Map(ir.schemas.map((schema) => [schema.id, schema]));
		this.#findInputs();
		this.#findLoosened();
		this.#checkNames();
	}

	get header(): string {
		return `// Generated by @nxgt/openapi-codegen from ${this.options.source}. Do not edit.`;
	}

	schema(id: string): NamedSchema {
		const schema = this.#byId.get(id);
		if (!schema) throw new Error(`openapi-codegen: no schema ${id}`);
		return schema;
	}

	/** Whether the schema needs a separate `XInput` type. */
	hasInput(id: string): boolean {
		return this.#inputs.has(id);
	}

	/** `Employee`, or `EmployeeInput` on the input side when the two differ. */
	typeName(id: string, input: boolean): string {
		const { name } = this.schema(id);
		const out = input && this.#inputs.has(id) ? `${name}Input` : name;
		this.#typeUses?.add(out);
		return out;
	}

	/**
	 * The node of a named schema printed as an `as const` object: an `enum` of
	 * two or more strings or numbers. `z.enum()` takes no booleans, and a
	 * single value is a constant, not a choice.
	 */
	enumOf(id: string): LiteralNode | undefined {
		if (this.options.enums !== 'object') return undefined;
		const { node } = this.schema(id);
		return node.kind === 'literal' &&
			node.values.length > 1 &&
			node.values.every(
				(value) => typeof value === 'string' || typeof value === 'number',
			)
			? node
			: undefined;
	}

	/** Runs `print`, and returns what it printed and every type name it used. */
	collectTypes<T>(print: () => T): { value: T; names: Set<string> } {
		const outer = this.#typeUses;
		const names = new Set<string>();
		this.#typeUses = names;
		try {
			return { value: print(), names };
		} finally {
			this.#typeUses = outer;
		}
	}

	resolve(node: SchemaNode): SchemaNode {
		let current = node;
		for (let hops = 0; current.kind === 'ref' && hops < 64; hops++) {
			current = this.schema(current.target).node;
		}
		return current;
	}

	/**
	 * The object's unknown-key mode. An intersection member keeps its own: a
	 * Zod intersection reports an unknown key only when every member does.
	 */
	mode(node: ObjectNode): ObjectMode {
		return node.additional === 'default'
			? this.options.unknownKeys
			: node.additional;
	}

	/** The mode of a named object schema. */
	modeOf(id: string): ObjectMode {
		const node = this.resolve(this.schema(id).node);
		return node.kind === 'object' ? this.mode(node) : 'strip';
	}

	/** A property of `object`, its own or one it extends. */
	propertyOf(
		object: ObjectNode,
		name: string,
		seen = new Set<string>(),
	): Property | undefined {
		const own = object.properties.find((p) => p.name === name);
		if (own) return own;
		for (const id of object.extends) {
			if (seen.has(id)) continue;
			seen.add(id);
			const parent = this.resolve(this.schema(id).node);
			if (parent.kind !== 'object') continue;
			const found = this.propertyOf(parent, name, seen);
			if (found) return found;
		}
		return undefined;
	}

	/**
	 * Whether the node's validator is a `ZodObject`, which `.extend()` and
	 * `discriminatedUnion` need. A recursive schema is typed `ZodType`, and an
	 * object built on one is an intersection.
	 */
	isZodObject(node: SchemaNode): boolean {
		if (node.nullable) return false;
		if (node.kind === 'ref') {
			const schema = this.schema(node.target);
			return !schema.recursive && this.isZodObject(schema.node);
		}
		return (
			node.kind === 'object' &&
			node.extends.every((target) => this.isZodObject({ kind: 'ref', target }))
		);
	}

	/** Whether the node's validator accepts something other than what it returns. */
	inputDiffers(node: SchemaNode): boolean {
		switch (node.kind) {
			case 'ref':
				return this.#inputs.has(node.target);
			case 'array':
				return this.inputDiffers(node.items);
			case 'record':
				return this.inputDiffers(node.values);
			case 'union':
				return node.variants.some((variant) => this.inputDiffers(variant));
			case 'intersection':
				return node.members.some((member) => this.inputDiffers(member));
			case 'object':
				return (
					node.extends.some((id) => this.#inputs.has(id)) ||
					node.properties.some(
						(p) => appliesDefault(p) || this.inputDiffers(p.schema),
					) ||
					(typeof node.additional === 'object' &&
						this.inputDiffers(node.additional.schema))
				);
			default:
				return false;
		}
	}

	/** To a fixpoint, since schemas can reach each other in cycles. */
	#findInputs(): void {
		let changed = true;
		while (changed) {
			changed = false;
			for (const schema of this.ir.schemas) {
				if (this.#inputs.has(schema.id) || !this.inputDiffers(schema.node)) {
					continue;
				}
				this.#inputs.add(schema.id);
				changed = true;
			}
		}
	}

	/**
	 * An `additionalProperties: false` on an `allOf` member that the generated
	 * validator cannot keep. JSON Schema refuses every key that member does not
	 * declare. A Zod intersection refuses a key only when every member does,
	 * and `.extend()` takes the child's mode, so beside a member that strips
	 * the extra keys are dropped instead.
	 */
	#findLoosened(): void {
		const refuses = (
			node: SchemaNode,
			seen = new Set<SchemaNode>(),
		): boolean => {
			const target = this.resolve(node);
			if (seen.has(target)) return true;
			seen.add(target);
			switch (target.kind) {
				case 'object':
					return this.mode(target) === 'strict';
				case 'union':
					return target.variants.every((v) => refuses(v, seen));
				case 'intersection':
					return target.members.some((m) => refuses(m, seen));
				default:
					return true;
			}
		};
		const said = (node: SchemaNode): boolean => {
			const target = this.resolve(node);
			return target.kind === 'object' && target.additional === 'strict';
		};
		for (const schema of this.ir.schemas) {
			let loosened = false;
			const visit = (node: SchemaNode): void => {
				if (node.kind === 'array') visit(node.items);
				else if (node.kind === 'record') visit(node.values);
				else if (node.kind === 'union') node.variants.forEach(visit);
				else if (node.kind === 'intersection') {
					if (
						node.members.some(said) &&
						!node.members.every((m) => refuses(m))
					) {
						loosened = true;
					}
					node.members.forEach(visit);
				} else if (node.kind === 'object') {
					const parents = node.extends.map(
						(target): SchemaNode => ({ kind: 'ref', target }),
					);
					const strict = this.mode(node) === 'strict';
					const kept = parents.every((p) => this.isZodObject(p))
						? strict
						: parents.every((p) => refuses(p)) &&
							(strict || node.properties.length === 0);
					if (parents.some(said) && !kept) loosened = true;
					for (const property of node.properties) visit(property.schema);
					if (typeof node.additional === 'object') {
						visit(node.additional.schema);
					}
				}
			};
			visit(schema.node);
			if (!loosened) continue;
			this.warnings.push({
				severity: 'warning',
				code: 'not_enforced',
				message: `${schema.name}: \`additionalProperties: false\` on an allOf member is not enforced. A key it does not declare is dropped, not refused, when another member accepts it`,
				file: schema.location.file,
				pointer: schema.location.pointer,
			});
		}
	}

	/**
	 * Every generated name, once. A schema's `XInput`, or an operation's
	 * `XQuery`, can land on a name a schema already has.
	 */
	#checkNames(): void {
		const owners = new Map<string, string>();
		const diagnostics: Diagnostic[] = [];
		const claim = (name: string, owner: string, at: Location): void => {
			const holder = owners.get(name);
			if (holder === undefined) {
				owners.set(name, owner);
				return;
			}
			diagnostics.push({
				severity: 'error',
				code: 'name_collision',
				message: `${holder} and ${owner} would both generate ${name}. Rename the schema with the \`names\` option`,
				file: at.file,
				pointer: at.pointer,
			});
		};
		for (const schema of this.ir.schemas) {
			claim(schema.name, `schema ${schema.name}`, schema.location);
		}
		for (const alias of this.ir.aliases) {
			claim(alias.name, `schema ${alias.name}`, alias.location);
		}
		for (const schema of this.ir.schemas) {
			if (this.#inputs.has(schema.id)) {
				claim(`${schema.name}Input`, `schema ${schema.name}`, schema.location);
			}
		}
		for (const alias of this.ir.aliases) {
			if (this.#inputs.has(alias.target)) {
				claim(`${alias.name}Input`, `schema ${alias.name}`, alias.location);
			}
		}
		for (const operation of this.ir.operations) {
			const owner = `operation ${operation.operationId}`;
			for (const group of paramGroups(operation)) {
				claim(group.name, owner, operation.location);
				if (group.hasInput) {
					claim(`${group.name}Input`, owner, operation.location);
				}
			}
		}
		if (diagnostics.length > 0) {
			throw new CodegenError(diagnostics, this.options.rootDir);
		}
	}
}
