/**
 * The generated code for each fixture, pinned as files under
 * `test/generated/`. `UPDATE_GOLDEN=1 bun test` rewrites them.
 *
 * Beside each case's output goes `agreement.ts`, one line per schema, which
 * the package's `tsc` fails on when a type and its validator disagree.
 */
import { describe, expect, it } from 'bun:test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateFiles } from '../generate';
import { buildIR } from '../ir';
import { loadDocument } from '../loader/document';
import { EmitContext } from './context';
import { file } from './printer';

const TEST = fileURLToPath(new URL('../../test/', import.meta.url));
const UPDATE = process.env.UPDATE_GOLDEN === '1';
const CASES = ['split', 'query', 'kitchen-sink'];

async function golden(path: string, content: string): Promise<void> {
	if (UPDATE) {
		await mkdir(dirname(path), { recursive: true });
		await writeFile(path, content);
		return;
	}
	const current = await readFile(path, 'utf8').catch(() => undefined);
	if (current === undefined) {
		throw new Error(
			`${relative(TEST, path)} is missing: run UPDATE_GOLDEN=1 bun test`,
		);
	}
	expect(content).toBe(current);
}

async function agreement(name: string): Promise<string> {
	const ir = buildIR(
		await loadDocument(`${TEST}fixtures/${name}/openapi.yaml`),
	);
	const ctx = new EmitContext(ir, {
		unknownKeys: 'strip',
		importExtension: '.js',
		source: '',
		rootDir: TEST,
	});
	const checks = [
		...ir.schemas.map((s) => ({ name: s.name, id: s.id })),
		...ir.aliases.map((a) => ({ name: a.name, id: a.target })),
	].flatMap(({ name, id }) => [
		`\tAgree<Equal<z.output<typeof Z.z${name}>, T.${name}>>,`,
		`\tAgree<Equal<z.input<typeof Z.z${name}>, T.${ctx.typeName(id, true).replace(ctx.schema(id).name, name)}>>,`,
	]);
	return file([
		'// Generated by src/emit/golden.spec.ts: tsc fails here when a type disagrees with its validator.',
		[
			"import type { z } from 'zod';",
			"import type * as T from './types.gen.js';",
			"import type * as Z from './zod.gen.js';",
		].join('\n'),
		[
			'type Equal<X, Y> = 0 extends 1 & X',
			'\t? false',
			'\t: 0 extends 1 & Y',
			'\t\t? false',
			'\t\t: [X] extends [Y]',
			'\t\t\t? [Y] extends [X]',
			'\t\t\t\t? true',
			'\t\t\t\t: false',
			'\t\t\t: false;',
			'type Agree<Result extends true> = Result;',
		].join('\n'),
		checks.length === 0
			? 'export type Agreement = [];'
			: `export type Agreement = [\n${checks.join('\n')}\n];`,
	]);
}

describe('generated code', () => {
	for (const name of CASES) {
		it(`matches the golden files for ${name}`, async () => {
			const output = `${TEST}generated/${name}`;
			const { files } = await generateFiles({
				input: `${TEST}fixtures/${name}/openapi.yaml`,
				output,
			});
			for (const generated of files) {
				await golden(generated.path, generated.content);
			}
			await golden(`${output}/agreement.ts`, await agreement(name));
		});
	}
});
