/**
 * A synthetic spec of `size` operations, and a file that registers a route
 * for each one: what `src/perf.spec.ts` gives `tsc --extendedDiagnostics`
 * to hold the typing of routes to a budget.
 */
export const PERF_SIZE = 500;

const json = (schema: object) => ({
	description: 'A reply.',
	content: { 'application/json': { schema } },
});

/** `size / 2` paths, each with a GET and a PUT, over ten shared schemas. */
export function perfSpec(size: number): object {
	const paths: Record<string, object> = {};
	for (let i = 0; i < size / 2; i++) {
		const item = { $ref: `#/components/schemas/Item${i % 10}` };
		const tags = [`t${i % 20}`];
		paths[`/r${i}/{id}`] = {
			parameters: [
				{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } },
			],
			get: {
				operationId: `get${i}`,
				tags,
				parameters: [
					{
						name: 'page',
						in: 'query',
						schema: { type: 'integer', default: 1 },
					},
				],
				responses: {
					200: json(item),
					404: json({ $ref: '#/components/schemas/Problem' }),
				},
			},
			put: {
				operationId: `put${i}`,
				tags,
				requestBody: {
					required: true,
					content: { 'application/json': { schema: item } },
				},
				responses: { 200: json(item) },
			},
		};
	}
	const schemas: Record<string, object> = {
		Problem: {
			type: 'object',
			required: ['message'],
			properties: { message: { type: 'string' } },
		},
	};
	for (let k = 0; k < 10; k++) {
		schemas[`Item${k}`] = {
			type: 'object',
			required: ['id', 'name'],
			properties: {
				id: { type: 'integer' },
				name: { type: 'string' },
				labels: { type: 'array', items: { type: 'string' } },
			},
		};
	}
	return {
		openapi: '3.1.0',
		info: { title: 'Perf', version: '1.0.0' },
		paths,
		components: { schemas },
	};
}

/** Every operation of `perfSpec(size)`, registered the way an app would. */
export function perfRoutes(size: number): string {
	const lines = [
		'// Generated by test/generate.ts: a route for each operation of the perf spec.',
		"import { Hono } from 'hono';",
		"import { createRoutes } from './hono.js';",
		'',
		'export const app = new Hono();',
		'const routes = createRoutes(app);',
		'',
	];
	for (let i = 0; i < size / 2; i++) {
		lines.push(
			`routes.get('/r${i}/{id}', (c) => c.json({ id: c.req.valid('param').id + c.req.valid('query').page, name: 'x' }, 200));`,
			`routes.put('/r${i}/{id}', (c) => c.json(c.req.valid('json'), 200));`,
		);
	}
	return `${lines.join('\n')}\n`;
}
